name = "vakdab"
main = "worker.js"
compatibility_date = "2026-08-09"

[assets]
directory = ".."
binding = "ASSETS"

[[kv_namespaces]]
binding = "MAKIMA_MEMORY"
id = "e895b4efdc7941c5915ca6af83879f96"

[[durable_objects.bindings]]
name = "CHAT_ROULETTE"
class_name = "ChatRouletteRoom"

[[migrations]]
tag = "roulette-v1"
new_sqlite_classes = ["ChatRouletteRoom"]
