// Mock firebase
export const initializeApp = () => {};
export const getAuth = () => {};
export const signInWithEmailAndPassword = () => {};
export const createUserWithEmailAndPassword = () => {};
export const signInWithPopup = () => {};
export const signInWithCustomToken = () => {};
export const GoogleAuthProvider = class {};
export const onAuthStateChanged = () => {};
export const signOut = () => {};
export const updateProfile = () => {};
export const setPersistence = () => {};
export const browserLocalPersistence = {};
export const signInAnonymously = () => {};
export const sendPasswordResetEmail = () => {};
export const deleteUser = () => {};
export const getFirestore = () => {};
export const doc = () => {};
export const getDoc = () => {};
export const setDoc = () => {};
export const deleteDoc = () => {};
export const updateDoc = () => {};
export const arrayUnion = () => {};
export const arrayRemove = () => {};
export const serverTimestamp = () => {};
export const addDoc = () => {};
export const collection = () => {};
export const query = () => {};
export const where = () => {};
export const orderBy = () => {};
export const limit = () => {};
export const onSnapshot = () => {};
export const getDocs = () => {};
export const getStorage = () => {};
export const ref = () => {};
export const uploadBytesResumable = () => {};
export const getDownloadURL = () => {};
export const deleteObject = () => {};
export const FIREBASE_CONFIG = {};
