import assert from 'node:assert/strict';
import test from 'node:test';
import { handleWatchPartyRequest, __watchPartyTest } from '../backend/telegram/watch-party.js';

class MockKV { constructor() { this.data = new Map(); } async get(key) { return this.data.get(key) ?? null; } async put(key, value) { this.data.set(key, value); } }
async function initData(botToken, user) { const params = new URLSearchParams({ auth_date: String(Math.floor(Date.now() / 1000)), user: JSON.stringify(user), query_id: 'watch-party-test' }); const secret = await crypto.subtle.sign('HMAC', await crypto.subtle.importKey('raw', new TextEncoder().encode('WebAppData'), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']), new TextEncoder().encode(botToken)); const key = await crypto.subtle.importKey('raw', secret, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); const check = [...params.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([keyName, value]) => `${keyName}=${value}`).join('\n'); const hash = [...new Uint8Array(await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(check)))].map(value => value.toString(16).padStart(2, '0')).join(''); params.set('hash', hash); return params.toString(); }
function request(init, action, payload) { return new Request('https://vakdab.animegran8.workers.dev/watch-party-api', { method: action ? 'POST' : 'GET', headers: { Origin: 'https://vakdab.animegran8.workers.dev', 'content-type': 'application/json', 'X-Telegram-Init-Data': init }, body: action ? JSON.stringify({ action, ...payload }) : undefined }); }
function mockCatalog() { return async () => new Response(JSON.stringify({ list: [{ id: 'a1', slug: 'demo-anime', title_ua: 'Demo Anime', image: 'https://img.example/demo.jpg', episodes_total: 12 }, { id: 'a2', slug: 'second-anime', title_ua: 'Second Anime', episodes_total: 8 }, { id: 'a3', slug: 'third-anime', title_ua: 'Third Anime', episodes_total: 10 }, { id: 'a4', slug: 'fourth-anime', title_ua: 'Fourth Anime', episodes_total: 6 }] }), { status: 200, headers: { 'content-type': 'application/json' } }); }

test('daily room creates four anime candidates automatically and persists them', async () => {
  const previousFetch = global.fetch; global.fetch = mockCatalog();
  try { const token = '123456:test-token'; const userInit = await initData(token, { id: 2, first_name: 'Viewer', username: 'viewer' }); const env = { TELEGRAM_BOT_TOKEN: token, MAKIMA_MEMORY: new MockKV() }; const response = await handleWatchPartyRequest(request(userInit, '', {}), env); assert.equal(response.status, 200); const snapshot = await response.json(); assert.match(snapshot.state.day, /^\d{4}-\d{2}-\d{2}$/); assert.equal(snapshot.state.status, 'anime_voting'); assert.equal(snapshot.state.candidates.length, 4); assert.ok(snapshot.state.candidates.every(candidate => candidate.siteUrl)); const second = await handleWatchPartyRequest(request(userInit, '', {}), env); assert.deepEqual((await second.json()).state.candidates, snapshot.state.candidates); } finally { global.fetch = previousFetch; }
});

test('users vote for anime and then separately vote for dub', async () => {
  const previousFetch = global.fetch; global.fetch = mockCatalog();
  try { const token = '123456:test-token'; const adminInit = await initData(token, { id: 1, first_name: 'Admin', username: 'vaditx' }); const viewerInit = await initData(token, { id: 2, first_name: 'Viewer', username: 'viewer' }); const env = { TELEGRAM_BOT_TOKEN: token, MAKIMA_MEMORY: new MockKV() }; const initial = await handleWatchPartyRequest(request(viewerInit, '', {}), env); const candidates = (await initial.json()).state.candidates; const winnerId = candidates[1].id;
    let response = await handleWatchPartyRequest(request(viewerInit, 'vote_anime', { candidateId: winnerId }), env); assert.equal(response.status, 200); response = await handleWatchPartyRequest(request(adminInit, 'vote_anime', { candidateId: winnerId }), env); assert.equal(response.status, 200);
    response = await handleWatchPartyRequest(request(adminInit, 'lock_anime', {}), env); assert.equal(response.status, 200); let state = (await response.json()).state; assert.equal(state.status, 'dub_voting'); assert.equal(state.anime.id, winnerId); assert.equal(state.candidates.length, 4);
    response = await handleWatchPartyRequest(request(viewerInit, 'catalog_meta', { dubs: ['AniLibria', 'UkrDub'], episodesTotal: 2 }), env); assert.equal(response.status, 403); response = await handleWatchPartyRequest(request(adminInit, 'catalog_meta', { dubs: ['AniLibria', 'UkrDub'], episodesTotal: 2 }), env); assert.equal(response.status, 200); response = await handleWatchPartyRequest(request(viewerInit, 'vote_dub', { dub: 'UkrDub' }), env); assert.equal(response.status, 200); response = await handleWatchPartyRequest(request(adminInit, 'vote_dub', { dub: 'UkrDub' }), env); assert.equal(response.status, 200);
    response = await handleWatchPartyRequest(request(viewerInit, 'vote_anime', { candidateId: candidates[0].id }), env); assert.equal(response.status, 409); response = await handleWatchPartyRequest(request(adminInit, 'start', {}), env); assert.equal(response.status, 200); state = (await response.json()).state; assert.equal(state.status, 'live'); assert.deepEqual(state.selection, { time: '20:00', dub: 'UkrDub', episodes: 1 });
  } finally { global.fetch = previousFetch; }
});

test('owner can start a test stream without a dub vote and uses the first available dub', async () => {
  const previousFetch = global.fetch; global.fetch = mockCatalog();
  try { const token = '123456:test-token'; const adminInit = await initData(token, { id: 1, first_name: 'Admin', username: 'vaditx' }); const env = { TELEGRAM_BOT_TOKEN: token, MAKIMA_MEMORY: new MockKV() }; const initial = await handleWatchPartyRequest(request(adminInit, '', {}), env); const candidate = (await initial.json()).state.candidates[0].id; await handleWatchPartyRequest(request(adminInit, 'vote_anime', { candidateId: candidate }), env); await handleWatchPartyRequest(request(adminInit, 'lock_anime', {}), env); await handleWatchPartyRequest(request(adminInit, 'catalog_meta', { dubs: ['UkrDub'], episodesTotal: 18 }), env); const start = await handleWatchPartyRequest(request(adminInit, 'start', {}), env); assert.equal(start.status, 200); const state = (await start.json()).state; assert.equal(state.status, 'live'); assert.equal(state.selection.dub, 'UkrDub'); assert.equal(state.anime.episodesTotal, 18);
  } finally { global.fetch = previousFetch; }
});

test('stale 999 episode metadata is sanitized and valid metadata is preserved', async () => {
  const previousFetch = global.fetch; global.fetch = mockCatalog();
  try { const token = '123456:test-token'; const adminInit = await initData(token, { id: 1, first_name: 'Admin', username: 'vaditx' }); const env = { TELEGRAM_BOT_TOKEN: token, MAKIMA_MEMORY: new MockKV() }; const day = __watchPartyTest.kyivDay(); const candidates = [{ id: 'a1', title: 'Current Anime', episodesTotal: 18 }, { id: 'a2', title: 'Second Anime', episodesTotal: 8 }]; await env.MAKIMA_MEMORY.put('watch-party:global:state', JSON.stringify({ roomId: 'global-anime-live', day, status: 'dub_voting', candidates, animeVotes: {}, dubVotes: {}, anime: { ...candidates[0], episodesTotal: 999, dubs: ['UkrDub'] }, selection: null, episode: 1, position: 0, playing: false, startedAt: null, finishedAt: null, messages: [] })); let response = await handleWatchPartyRequest(request(adminInit, '', {}), env); assert.equal(response.status, 200); assert.equal((await response.json()).state.anime.episodesTotal, 18); response = await handleWatchPartyRequest(request(adminInit, 'catalog_meta', { dubs: ['UkrDub'], episodesTotal: 999 }), env); assert.equal(response.status, 200); assert.equal((await response.json()).state.anime.episodesTotal, 18);
  } finally { global.fetch = previousFetch; }
});

test('current anime stays locked until every episode is completed', async () => {
  const previousFetch = global.fetch; global.fetch = mockCatalog();
  try { const token = '123456:test-token'; const adminInit = await initData(token, { id: 1, first_name: 'Admin', username: 'vaditx' }); const env = { TELEGRAM_BOT_TOKEN: token, MAKIMA_MEMORY: new MockKV() }; const response = await handleWatchPartyRequest(request(adminInit, '', {}), env); const candidate = (await response.json()).state.candidates[0].id; await handleWatchPartyRequest(request(adminInit, 'vote_anime', { candidateId: candidate }), env); await handleWatchPartyRequest(request(adminInit, 'lock_anime', {}), env); await handleWatchPartyRequest(request(adminInit, 'catalog_meta', { dubs: ['UkrDub'], episodesTotal: 2 }), env); await handleWatchPartyRequest(request(adminInit, 'vote_dub', { dub: 'UkrDub' }), env); await handleWatchPartyRequest(request(adminInit, 'start', {}), env);
    let next = await handleWatchPartyRequest(request(adminInit, 'next_episode', {}), env); assert.equal(next.status, 409); next = await handleWatchPartyRequest(request(adminInit, 'next_episode', { completed: true }), env); let state = (await next.json()).state; assert.equal(state.status, 'live'); assert.equal(state.episode, 2); next = await handleWatchPartyRequest(request(adminInit, 'next_episode', { completed: true }), env); state = (await next.json()).state; assert.equal(state.status, 'finished'); assert.equal(state.episode, 2); const reset = await handleWatchPartyRequest(request(adminInit, 'reset', {}), env); assert.equal(reset.status, 200); assert.equal((await reset.json()).state.status, 'anime_voting');
  } finally { global.fetch = previousFetch; }
});

test('live chat persists messages and returns them to other authenticated viewers', async () => {
  const previousFetch = global.fetch; global.fetch = mockCatalog();
  try { const token = '123456:test-token'; const adminInit = await initData(token, { id: 1, first_name: 'Admin', username: 'vaditx' }); const viewerInit = await initData(token, { id: 2, first_name: 'Viewer', username: 'viewer' }); const env = { TELEGRAM_BOT_TOKEN: token, MAKIMA_MEMORY: new MockKV() }; const initial = await handleWatchPartyRequest(request(adminInit, '', {}), env); const candidate = (await initial.json()).state.candidates[0].id; await handleWatchPartyRequest(request(adminInit, 'vote_anime', { candidateId: candidate }), env); await handleWatchPartyRequest(request(adminInit, 'lock_anime', {}), env); await handleWatchPartyRequest(request(adminInit, 'catalog_meta', { dubs: ['UkrDub'], episodesTotal: 18 }), env); await handleWatchPartyRequest(request(adminInit, 'start', {}), env); const sent = await handleWatchPartyRequest(request(viewerInit, 'chat', { text: 'Перевірка чату' }), env); assert.equal(sent.status, 200); const state = (await sent.json()).state; assert.equal(state.messages[0].text, 'Перевірка чату'); const received = await handleWatchPartyRequest(request(adminInit, '', {}), env); assert.equal((await received.json()).state.messages[0].text, 'Перевірка чату');
  } finally { global.fetch = previousFetch; }
});

test('non-admin users cannot lock anime, start, reset or manage the room', async () => { const previousFetch = global.fetch; global.fetch = mockCatalog(); try { const token = '123456:test-token'; const viewerInit = await initData(token, { id: 2, first_name: 'Viewer', username: 'viewer' }); const env = { TELEGRAM_BOT_TOKEN: token, MAKIMA_MEMORY: new MockKV() }; assert.equal((await handleWatchPartyRequest(request(viewerInit, 'lock_anime', {}), env)).status, 403); assert.equal((await handleWatchPartyRequest(request(viewerInit, 'start', {}), env)).status, 403); assert.equal((await handleWatchPartyRequest(request(viewerInit, 'reset', {}), env)).status, 403); assert.equal((await handleWatchPartyRequest(request(viewerInit, 'catalog_meta', { dubs: ['FakeDub'], episodesTotal: 1 }), env)).status, 403); } finally { global.fetch = previousFetch; } });
