// Watch Party v11 frontend asset
const WATCH_PARTY_ORIGIN = location.hostname.endsWith('.workers.dev') ? location.origin : 'https://vakdab.animegran8.workers.dev';
const WATCH_API_BASE = `${WATCH_PARTY_ORIGIN}/watch-party-api`;
const HIKKA_PROXY = 'https://vakdab-hikka-proxy.animegran8.workers.dev';
const SOURCE_PROXY = 'https://monoanime.animegran8.workers.dev';
const LOCAL_SOURCE_PROXY = `${WATCH_PARTY_ORIGIN}/watch-party-source`;
const MAX_EPISODES = 100;
const tg = globalThis.Telegram?.WebApp;
if (tg) { tg.ready(); tg.expand(); tg.setHeaderColor?.('#000'); tg.setBackgroundColor?.('#000'); }
const state = { data: null, user: null, detail: null, detailKey: '', sourceCache: new Map(), sourceLoading: '', hls: null, pollTimer: null, syncTimer: null, controlTimer: null, lastControlAt: 0 };
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
function showToast(message) { const toast = $('toast'); if (!toast) return; toast.textContent = message; toast.classList.add('is-visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('is-visible'), 3000); }
async function request(action = '', payload = {}) { const headers = { 'content-type': 'application/json' }; if (tg?.initData) headers['X-Telegram-Init-Data'] = tg.initData; const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 15000); try { const response = await fetch(WATCH_API_BASE, { method: action ? 'POST' : 'GET', headers, body: action ? JSON.stringify({ action, ...payload }) : undefined, signal: controller.signal }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || `Watch Party ${response.status}`); return result; } catch (error) { if (error?.name === 'AbortError') throw new Error('Сервер довго не відповідає'); throw error; } finally { clearTimeout(timeout); } }
function currentAnime() { return state.data?.anime || null; }
function countFor(id) { return Number(state.data?.candidateCounts?.[id] || 0); }
function bestCandidate() { const candidates = state.data?.candidates || []; return candidates.slice().sort((a, b) => countFor(b.id) - countFor(a.id) || String(a.title).localeCompare(String(b.title)))[0]; }
function statusLabel(status) { return ({ anime_voting: 'Голосування за аніме', dub_voting: 'Голосування за озвучку', live: 'Ефір наживо', finished: 'День завершено' })[status] || 'Завантаження'; }
function renderState() {
  const data = state.data || {}; const anime = currentAnime(); const status = data.status || 'anime_voting'; const live = status === 'live'; const finished = status === 'finished';
  $('roomState').textContent = statusLabel(status); $('roomState').classList.toggle('is-live', live);
  $('heroStatus').textContent = live ? `Зараз дивимось: ${anime?.title || 'Аніме'}` : finished ? 'Новий random буде завтра' : status === 'dub_voting' ? `Аніме обрано: ${anime?.title || 'очікуємо'}` : `Вибір на ${data.day || 'сьогодні'}`;
  $('stepKicker').textContent = status === 'anime_voting' ? '01 · Обери аніме' : status === 'dub_voting' ? '02 · Обери озвучку' : '03 · Спільний ефір';
  $('pollQuestion').textContent = status === 'anime_voting' ? 'За яке аніме голосуємо?' : status === 'dub_voting' ? 'Якою озвучкою дивимось?' : live ? 'Зараз дивимось разом' : 'Сьогоднішній ефір завершено';
  $('dailyHint').textContent = status === 'anime_voting' ? 'Обери один із чотирьох варіантів. Один голос на користувача.' : status === 'dub_voting' ? 'Голосування за аніме завершене. Тепер обираємо озвучку.' : anime ? `${anime.title} · прогрес серій зберігається` : 'VakDab Watch Party';
  $('scheduleAnime').textContent = anime?.title || 'Очікуємо вибір'; $('scheduleDub').textContent = live || finished ? (data.selection?.dub || '—') : status === 'dub_voting' ? 'Голосування' : '—'; $('scheduleProgress').textContent = anime ? `Серія ${data.episode || 1} / ${anime.episodesTotal || '—'}` : '—'; $('scheduleStatus').textContent = statusLabel(status);
  $('lockTitle').textContent = status === 'anime_voting' ? 'Спочатку обираємо аніме' : status === 'dub_voting' ? 'Аніме вже зафіксоване' : finished ? 'Тайтл повністю завершено' : 'Новий random заблоковано';
  $('lockText').textContent = status === 'anime_voting' ? 'Після перемоги відкриється окреме голосування за озвучку.' : status === 'dub_voting' ? 'Поки триває цей етап, усі голосують тільки за озвучку.' : finished ? 'Наступний пул із чотирьох аніме з’явиться на новий київський день.' : 'Наступний пул не відкриється, доки всі серії цього аніме не завершені.';
  $('animeSiteLink').hidden = !anime?.siteUrl; if (anime?.siteUrl) $('animeSiteLink').href = anime.siteUrl; const poster = $('animePoster'); poster.innerHTML = anime?.posterUrl ? `<img src="${esc(anime.posterUrl)}" alt="" loading="eager">` : '<span>V</span>'; $('animeTitle').textContent = anime?.title || 'Переможець з’явиться після голосування'; $('animeMeta').textContent = anime ? `${anime.episodesTotal || '—'} серій у каталозі VakDab` : 'Чотири випадкові варіанти з каталогу VakDab';
  $('scheduleTime').textContent = '20:00'; $('viewerCount').textContent = String(Math.max(1, Object.keys(data.candidateCounts || {}).length));
  renderCandidates(); renderDubs(); renderChat(); renderResults(); renderAdmin(); renderParty();
}
function renderCandidates() { const data = state.data || {}; const list = $('candidateList'); const candidates = Array.isArray(data.candidates) ? data.candidates : []; const active = data.status === 'anime_voting'; if (!candidates.length) { list.innerHTML = '<div class="state-card">Завантажуємо варіанти аніме…</div>'; return; } if (!active) { const anime = data.anime; list.innerHTML = anime ? `<div class="winner-card"><span class="winner-mark">✓</span><div><span class="candidate-label">Переможець голосування</span><strong>${esc(anime.title)}</strong><small>Тайтл зафіксовано для цієї кімнати</small></div></div>` : '<div class="state-card">Переможець ще не визначений.</div>'; return; } list.innerHTML = candidates.map((candidate, index) => { const selected = data.myAnimeVote === candidate.id; return `<button type="button" class="candidate-card${selected ? ' is-selected' : ''}" data-candidate-id="${esc(candidate.id)}"><span class="candidate-number">0${index + 1}</span><span class="candidate-poster">${candidate.posterUrl ? `<img src="${esc(candidate.posterUrl)}" alt="" loading="lazy">` : 'V'}</span><span class="candidate-copy"><span class="candidate-label">Варіант ${index + 1}</span><strong>${esc(candidate.title)}</strong><small>${candidate.episodesTotal || '—'} серій · VakDab</small></span><span class="vote-count">${countFor(candidate.id)}<small>голосів</small></span></button>`; }).join(''); }
function renderDubs() { const data = state.data || {}; const block = $('dubVoteBlock'); const active = data.status === 'dub_voting'; block.hidden = !['dub_voting', 'live', 'finished'].includes(data.status); if (data.status !== 'dub_voting') { $('dubList').innerHTML = data.selection ? `<div class="winner-card"><span class="winner-mark">✓</span><div><span class="candidate-label">Обрана озвучка</span><strong>${esc(data.selection.dub)}</strong><small>Синхронний ефір VakDab</small></div></div>` : '<div class="state-card">Озвучка з’явиться після вибору аніме.</div>'; return; } const dubs = Array.isArray(data.anime?.dubs) && data.anime.dubs.length ? data.anime.dubs : (state.detail?.dubs || []); if (!dubs.length) { $('dubList').innerHTML = '<div class="state-card">Завантажуємо озвучки з VakDab…</div>'; return; } $('dubList').innerHTML = dubs.map(dub => { const selected = data.myDubVote === dub; const votes = Number(data.dubCounts?.[dub] || 0); return `<button type="button" class="dub-card${selected ? ' is-selected' : ''}" data-dub="${esc(dub)}"><span class="radio-mark">${selected ? '✓' : ''}</span><span><strong>${esc(dub)}</strong><small>${votes} голосів</small></span></button>`; }).join(''); if (!active) $('dubVoteBlock').classList.add('is-locked'); }
function renderChat() { const list = $('chatMessages'); const messages = Array.isArray(state.data?.messages) ? state.data.messages : []; list.innerHTML = messages.length ? messages.map(message => `<article class="chat-message"><strong>${esc(message.name || message.username || 'Глядач')}</strong><time>${esc(new Date(Number(message.at || Date.now())).toLocaleTimeString('uk-UA', { hour: '2-digit', minute: '2-digit' }))}</time><p>${esc(message.text)}</p></article>`).join('') : '<div class="chat-empty">Поки що немає повідомлень. Напиши першим.</div>'; list.scrollTop = list.scrollHeight; }
function renderResults() { const data = state.data || {}; if (data.status === 'anime_voting') { const best = bestCandidate(); $('resultsContent').innerHTML = best ? `<div class="result-row"><span>Лідер</span><strong>${esc(best.title)} <small>${countFor(best.id)} голосів</small></strong></div><div class="result-row"><span>Усього голосів</span><strong>${Object.values(data.candidateCounts || {}).reduce((sum, value) => sum + Number(value || 0), 0)}</strong></div>` : 'Ще немає голосів.'; } else if (data.status === 'dub_voting') { const counts = data.dubCounts || {}; const best = Object.entries(counts).sort((a, b) => b[1] - a[1])[0]; $('resultsContent').innerHTML = best ? `<div class="result-row"><span>Лідер озвучки</span><strong>${esc(best[0])} <small>${best[1]} голосів</small></strong></div>` : 'Ще немає голосів за озвучку.'; } else $('resultsContent').innerHTML = data.selection ? `<strong>${esc(data.selection.dub)}</strong> · серія ${data.episode || 1}` : 'Ефір очікує запуску.'; }
function renderAdmin() { const admin = Boolean(state.user?.isAdmin); $('adminPanel').hidden = !admin; if (!admin) return; const status = state.data?.status; $('lockAnimeButton').hidden = status !== 'anime_voting'; $('startButton').hidden = status !== 'dub_voting'; $('startHint').hidden = status !== 'dub_voting'; $('nextEpisodeButton').hidden = status !== 'live'; $('resetButton').hidden = status !== 'finished'; $('adminStatus').textContent = status === 'anime_voting' ? 'Дочекайся голосів і зафіксуй аніме' : status === 'dub_voting' ? 'Можна проголосувати за озвучку або одразу натиснути «Почати ефір»' : status === 'live' ? 'Ефір триває' : 'Після повного завершення можна відкрити новий random'; }
function episodeEntry() { const detail = state.detail; const selection = state.data?.selection; if (!detail || !selection) return null; const season = detail.seasons?.[Object.keys(detail.seasons || {})[0] || '1'] || {}; const list = season[selection.dub] || Object.values(season).find(value => Array.isArray(value) && value.length) || []; return list.find(item => Number(item.episode) === Number(state.data.episode)) || list[0] || null; }
function extractHlsManifest(html) { const normalized = String(html || '').replaceAll('\\\\u002F', '/').replaceAll('\\\\/', '/').replaceAll('&amp;', '&'); const matches = normalized.match(/https?:\/\/[^\s"'<>`,]+\.m3u8(?:\?[^\s"'<>`,]*)?/gi) || []; return matches.find(url => /ashdi\.vip|video/i.test(url)) || matches[0] || ''; }
function attachVideoSource(video, source) { if (state.hls) { state.hls.destroy(); state.hls = null; } if (!source) return; const Hls = globalThis.Hls; if (Hls?.isSupported?.()) { const hls = new Hls({ enableWorker: true, lowLatencyMode: false, backBufferLength: 30 }); hls.on(Hls.Events.MANIFEST_PARSED, () => { if (state.data?.playing) video.play().catch(() => {}); }); hls.on(Hls.Events.ERROR, (_event, details) => { if (details?.fatal) showToast('Не вдалося завантажити HLS-відео'); }); hls.loadSource(source); hls.attachMedia(video); state.hls = hls; } else { video.src = source; video.load(); } }
function renderParty() { const data = state.data || {}; const live = data.status === 'live' && data.selection; $('partySection').hidden = !live; if (!live) return; $('streamTitle').textContent = data.anime?.title || 'Трансляція'; $('episodeLabel').textContent = `Серія ${data.episode || 1} з ${data.anime?.episodesTotal || '—'}`; $('syncBadge').textContent = state.user?.isAdmin ? 'Ти ведеш ефір' : 'Синхронізовано'; $('siteLink').hidden = !data.anime?.siteUrl; if (data.anime?.siteUrl) $('siteLink').href = data.anime.siteUrl; const entry = episodeEntry(); const rawSource = String(entry?.file || '').trim(); const needsResolve = rawSource.toLowerCase().includes('ashdi.vip/vod/'); const source = state.sourceCache.get(rawSource) || (needsResolve ? '' : rawSource); const video = $('partyVideo'); video.setAttribute('crossorigin', 'anonymous'); video.setAttribute('type', 'application/vnd.apple.mpegurl'); if (source && video.dataset.source !== source) { video.dataset.source = source; attachVideoSource(video, source); video.dataset.source = source; } if (!source && video.dataset.source) { if (state.hls) { state.hls.destroy(); state.hls = null; } video.dataset.source = ''; video.removeAttribute('src'); video.load(); } $('videoEmpty').hidden = !source; $('videoEmpty').querySelector('strong').textContent = needsResolve ? 'Підключаємо ASHDI через VakDab' : state.detail ? 'Відео готується' : 'Завантажуємо серію з VakDab'; $('streamSourceLabel').textContent = `${data.selection.dub || 'Озвучка'} · джерело VakDab`; if (needsResolve && !source) prepareVideoSource(rawSource); }
async function prepareVideoSource(rawSource) { if (!rawSource || state.sourceCache.has(rawSource) || state.sourceLoading === rawSource) return; state.sourceLoading = rawSource; try { const response = await fetch(`${LOCAL_SOURCE_PROXY}?url=${encodeURIComponent(rawSource)}&force_ua=desktop`, { headers: { accept: 'text/html,application/xhtml+xml' }, signal: AbortSignal.timeout(20000) }); if (!response.ok) throw new Error(`ASHDI proxy ${response.status}`); const manifest = extractHlsManifest(await response.text()); if (!manifest) throw new Error('ASHDI manifest не знайдено'); const forceUA = /Android|iPhone|iPad|iPod/i.test(navigator.userAgent || '') ? 'mobile' : 'desktop'; state.sourceCache.set(rawSource, `${LOCAL_SOURCE_PROXY}?url=${encodeURIComponent(manifest)}&force_ua=${forceUA}`); renderParty(); } catch (error) { console.warn('[Watch Party] source resolve:', error); showToast('Серія поки недоступна через source proxy'); } finally { state.sourceLoading = ''; } }
async function loadState(silent = true) { try { const result = await request(); state.data = result.state || {}; state.user = result.user || null; $('profileName').textContent = state.user?.name || 'Мій профіль'; renderState(); await loadCatalogDetails(); renderState(); syncVideo(); } catch (error) { console.warn('[Watch Party] load:', error); const auth = /telegram|401|некоректні дані/i.test(String(error?.message || '')); $('roomState').textContent = auth ? 'Відкрий через Telegram' : 'Немає з’єднання'; $('candidateList').innerHTML = auth ? '<div class="state-card"><strong>Відкрий Anime Live у Telegram</strong><small>Голосування та чат доступні лише всередині Telegram Mini App.</small></div>' : '<div class="state-card"><strong>Не вдалося завантажити кімнату</strong><small>Перевір з’єднання та натисни кнопку оновлення.</small></div>'; if (!silent) showToast(auth ? 'Відкрий Watch Party через Telegram' : (error.message || 'Немає з’єднання')); } }
async function loadCatalogDetails() { const catalogUrl = String(state.data?.anime?.catalogUrl || ''); if (!catalogUrl || state.detailKey === catalogUrl || state.data?.status === 'anime_voting') return; state.detailKey = catalogUrl; try { const response = await fetch(`${HIKKA_PROXY}/?url=${encodeURIComponent(catalogUrl)}`, { headers: { accept: 'application/json' }, signal: AbortSignal.timeout(15000) }); if (!response.ok) throw new Error(`Hikka ${response.status}`); const anime = await response.json(); const external = Array.isArray(anime.external) ? anime.external : []; const mikai = external.find(item => String(item?.url || '').toLowerCase().includes('mikai.me/anime'))?.url || ''; const animeOn = external.find(item => String(item?.url || '').toLowerCase().includes('animeon.club/anime'))?.url || ''; if (mikai) { const htmlResponse = await fetch(`${SOURCE_PROXY}/?url=${encodeURIComponent(mikai)}&force_ua=desktop`, { headers: { accept: 'text/html,application/xhtml+xml' }, signal: AbortSignal.timeout(20000) }); state.detail = parseMikaiDetails(await htmlResponse.text()); } else if (animeOn) state.detail = await loadAnimeOnDetails(animeOn); else state.detail = { dubs: [], seasons: {} }; const dubs = state.detail.dubs || []; if (dubs.length && state.data?.status === 'dub_voting' && state.user?.isAdmin) { const episodeNumbers = Object.values(state.detail.seasons || {}).flatMap(season => Object.values(season).flatMap(list => list.map(item => Number(item.episode)).filter(number => Number.isInteger(number) && number >= 1 && number <= MAX_EPISODES && number !== 999))); const meta = { dubs }; if (episodeNumbers.length) meta.episodesTotal = Math.max(...episodeNumbers); const result = await request('catalog_meta', meta); state.data = result.state || state.data; } } catch (error) { console.warn('[Watch Party] catalog details:', error); state.detail = { dubs: [], seasons: {} }; } }
async function loadAnimeOnDetails(animeOnUrl) { const id = String(animeOnUrl).split('/anime/')[1]?.match(/^\d+/)?.[0]; if (!id) return { dubs: [], seasons: {} }; const fetchJson = async path => { const response = await fetch(`${SOURCE_PROXY}/?url=${encodeURIComponent(path)}`, { headers: { accept: 'application/json' }, signal: AbortSignal.timeout(15000) }); if (!response.ok) throw new Error(`AnimeON ${response.status}`); return response.json(); }; const data = await fetchJson(`https://animeon.club/api/player/${id}/translations`); const selected = (Array.isArray(data?.translations) ? data.translations : []).slice().sort((a, b) => (Number(b?.player?.[0]?.episodesCount) || 0) - (Number(a?.player?.[0]?.episodesCount) || 0)).find(item => (item?.player || []).some(player => Number(player?.episodesCount) > 0)); const translation = selected?.translation; const player = (selected?.player || []).slice().sort((a, b) => (Number(b?.episodesCount) || 0) - (Number(a?.episodesCount) || 0))[0]; if (!translation || !player) return { dubs: [], seasons: {} }; const episodesData = await fetchJson(`https://animeon.club/api/player/${id}/episodes?take=100&skip=-1&playerId=${encodeURIComponent(player.id)}&translationId=${encodeURIComponent(translation.id)}&includeAlternative=true`); const loaded = await Promise.all((episodesData?.episodes || []).map(async ref => { try { const episode = await fetchJson(`https://animeon.club/api/player/${encodeURIComponent(ref.id)}/episode`); return episode?.videoUrl ? { episode: String(ref.episode), file: String(episode.videoUrl), dub: String(translation.name || 'AnimeON') } : null; } catch { return null; } })); const list = loaded.filter(Boolean).sort((a, b) => Number(a.episode) - Number(b.episode)); const dub = String(translation.name || 'AnimeON'); return { dubs: list.length ? [dub] : [], seasons: list.length ? { '1': { [dub]: list } } : {} }; }
function normalizeEpisodeNumber(value) { const number = Number(value); return Number.isInteger(number) && number >= 1 && number <= MAX_EPISODES && number !== 999 ? String(number) : ''; }
function resolveNuxt(payload) { const memo = new Map(); const resolving = new Set(); const resolve = index => { if (!Number.isInteger(index) || index < 0 || index >= payload.length) return index; if (memo.has(index)) return memo.get(index); if (resolving.has(index)) return null; resolving.add(index); const raw = payload[index]; let value; if(typeof raw === 'number') value = raw; else if (Array.isArray(raw)) { const tag = typeof raw[0] === 'string' ? raw[0] : ''; value = ['ShallowReactive', 'Reactive', 'Set', 'Date', 'URL'].includes(tag) && raw.length > 1 ? resolve(raw[1]) : raw.map(item => typeof item === 'number' ? resolve(item) : item); } else if (raw && typeof raw === 'object') value = Object.fromEntries(Object.entries(raw).map(([key, item]) => [key, typeof item === 'number' ? resolve(item) : item])); else value = raw; resolving.delete(index); memo.set(index, value); return value; }; return payload.map((_, index) => resolve(index)); }
function parseMikaiDetails(html) { const match = String(html || '').match(/<script[^>]+id=["']__NUXT_DATA__["'][^>]*>([\s\S]*?)<\/script>/i); if (!match) return { dubs: [], seasons: {} }; let payload; try { payload = JSON.parse(match[1]); } catch { return { dubs: [], seasons: {} }; } const seasons = {}; const names = new Set(); resolveNuxt(payload).forEach(value => { if (!Array.isArray(value?.players)) return; value.players.forEach(group => { if (!group || !Array.isArray(group.providers) || group.isSubs) return; const team = String(group.team?.name || 'Озвучка сайту').trim(); const episodes = []; group.providers.filter(provider => String(provider?.name || '').toUpperCase() === 'ASHDI').forEach(provider => (provider.episodes || []).forEach(ep => { const number = normalizeEpisodeNumber(ep?.number); const file = String(ep?.playLink || '').trim(); if (number && file && !episodes.some(item => item.episode === number)) episodes.push({ episode: number, file: file.includes('?') ? `${file}&nopl` : `${file}?nopl`, dub: team }); })); if (episodes.length) { episodes.sort((a, b) => Number(a.episode) - Number(b.episode)); names.add(team); seasons['1'] ||= {}; seasons['1'][team] = episodes; } }); }); return { dubs: [...names], seasons }; }
async function perform(action, payload = {}) { try { const result = await request(action, payload); state.data = result.state || state.data; state.user = result.user || state.user; renderState(); showToast(action === 'start' ? 'Ефір запущено' : 'Збережено'); return true; } catch (error) { showToast(error.message || 'Дія не виконана'); return false; } }
function bindEvents() { $('refreshButton').addEventListener('click', () => loadState(false)); $('profileButton').addEventListener('click', () => { if (!tg?.initData) { location.href = 'https://t.me/vakluna?startapp=watch-party'; return; } showToast(state.user?.name || 'Профіль відкрито'); }); $('candidateList').addEventListener('click', event => { const card = event.target.closest('[data-candidate-id]'); if (card) perform('vote_anime', { candidateId: card.dataset.candidateId }); }); $('dubList').addEventListener('click', event => { const card = event.target.closest('[data-dub]'); if (card) perform('vote_dub', { dub: card.dataset.dub }); }); $('lockAnimeButton').addEventListener('click', () => perform('lock_anime')); $('startButton').addEventListener('click', () => perform('start')); $('nextEpisodeButton').addEventListener('click', () => perform('next_episode', { completed: true })); $('resetButton').addEventListener('click', () => perform('reset')); $('chatForm').addEventListener('submit', async event => { event.preventDefault(); const input = $('chatInput'); const text = input.value.trim(); if (!text || state.data?.status !== 'live') return; input.disabled = true; const sent = await perform('chat', { text }); if (sent) input.value = ''; input.disabled = false; }); const video = $('partyVideo'); $('videoEmpty').addEventListener('click', () => { const source = state.sourceCache.get(String(episodeEntry()?.file || '').trim()); if (source) video.play().catch(() => showToast('Натисни кнопку відтворення у відео')); else { const rawSource = String(episodeEntry()?.file || '').trim(); if (rawSource) prepareVideoSource(rawSource); } }); video.addEventListener('play', () => scheduleControl(true)); video.addEventListener('pause', () => scheduleControl(true)); video.addEventListener('seeked', () => scheduleControl(true)); video.addEventListener('timeupdate', () => scheduleControl(false)); video.addEventListener('ended', () => { if (state.user?.isAdmin) perform('next_episode', { completed: true }); }); video.addEventListener('error', () => { if (state.user?.isAdmin) showToast('Не вдалося завантажити серію з VakDab'); }); }
function scheduleControl(force = false) { if (!state.user?.isAdmin || state.data?.status !== 'live') return; const video = $('partyVideo'); const now = Date.now(); if (!force && now - state.lastControlAt < 1500) return; state.lastControlAt = now; clearTimeout(state.controlTimer); state.controlTimer = setTimeout(() => request('control', { playing: !video.paused, position: Number(video.currentTime || 0) }).catch(() => {}), force ? 0 : 200); }
function expectedPosition() { const data = state.data; if (!data || data.status !== 'live') return 0; return Math.max(0, Number(data.position || 0) + (data.playing ? (Date.now() - Number(data.updatedAt || Date.now())) / 1000 : 0)); }
function syncVideo() { const video = $('partyVideo'); if (!state.data || state.data.status !== 'live' || !video.dataset.source) return; const expected = expectedPosition(); if (Math.abs(video.currentTime - expected) > 3) { try { video.currentTime = expected; } catch {} } if (state.data.playing && video.paused) video.play().catch(() => {}); if (!state.data.playing && !video.paused) video.pause(); }
async function init() { bindEvents(); await loadState(false); state.pollTimer = setInterval(() => loadState(true), 5000); state.syncTimer = setInterval(syncVideo, 1000); }
init().catch(error => { console.error('[Watch Party] init failed:', error); showToast('Не вдалося запустити Watch Party'); });
